apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
  namespace: replaced-by-kustomize
spec:
  template:
    spec:
      initContainers:
        - name: install-audio-deps
          image: docker.io/vllm/vllm-openai:v0.11.0
          command: ["pip", "install", "--quiet", "vllm[audio]"]
